// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	activityreporter "git.garena.com/sea-labs-id/bootcamp/batch-03/maulana-jaelani/assignment-activity-reporter/-/tree/dev/activityreporter"
	mock "github.com/stretchr/testify/mock"
)

// Observer is an autogenerated mock type for the Observer type
type Observer struct {
	mock.Mock
}

// UpdateLikePhoto provides a mock function with given fields: userObject, ownerPhoto
func (_m *Observer) UpdateLikePhoto(userObject *activityreporter.User, ownerPhoto *activityreporter.User) {
	_m.Called(userObject, ownerPhoto)
}

// UpdateUploadPhoto provides a mock function with given fields: userObject
func (_m *Observer) UpdateUploadPhoto(userObject *activityreporter.User) {
	_m.Called(userObject)
}
